colum_headers = ["""
'company_id', 'Employees', 'Facebook Likes', 'Growth Rate',
       'Last Financing Size', 'Majestic Referring Domains', 'Size Multiple',
       'Total Raised', 'Twitter Followers', 'Year Founded',


       'agreeableness_big5', 'analytical', 'anger', 'confident',
       'conscientiousness_big5', 'disgust', 'emotional_range_big5',
       'extraversion_big5', 'fear', 'joy', 'openness_big5', 'sadness',
       'tentative', 'HQ_post_code',

       'Aerospace and Defense',
       'Alternative Energy Equipment', 'Application Software',
       'Application Specific Semiconductors', 'Automation/Workflow Software',
       'Automotive', 'Beverages', 'Biotechnology',
       'Broadcasting, Radio and Television', 'Business/Productivity Software',
       'Communication Software', 'Consulting Services (B2B)',
       'Consumer Finance', 'Database Software', 'Diagnostic Equipment',
       'Drug Discovery', 'Education and Training Services (B2B)',
       'Educational and Training Services (B2C)', 'Electrical Equipment',
       'Electronic Components', 'Electronics (B2C)', 'Energy Exploration',
       'Energy Production', 'Enterprise Systems (Healthcare)',
       'Entertainment Software', 'Environmental Services (B2B)',
       'Financial Software', 'Food Products', 'General Purpose Semiconductors',
       'Hotels and Resorts', 'Human Capital Services',
       'Information Services (B2C)', 'Internet Retail', 'Legal Services (B2C)',
       'Leisure Facilities', 'Logistics',
       'Media and Information Services (B2B)',
       'Movies, Music and Entertainment', 'Multimedia and Design Software',
       'Network Management Software', 'Other Business Products and Services',
       'Other Commercial Products', 'Other Commercial Services',
       'Other Consumer Durables', 'Other Consumer Products and Services',
       'Other Devices and Supplies', 'Other Energy Services',
       'Other Financial Services', 'Other Healthcare Services',
       'Other Healthcare Technology Systems', 'Other IT Services',
       'Other Information Technology', 'Other Restaurants, Hotels and Leisure',
       'Other Services (B2C Non-Financial)', 'Other Software',
       'Other Transportation', 'Personal Products', 'Private Equity',
       'Publishing', 'Real Estate Services (B2C)', 'Recreational Goods',
       'Restaurants and Bars', 'Security Services (B2B)', 'Social Content',
       'Social/Platform Software', 'Specialty Retail', 'Surgical Devices',
       'Therapeutic Devices', 'Vertical Market Software', 'Water Utilities',
       'Wireless Service Providers'


service_tier_gold, service_tier_silver, service_tier_bronze,
size_of_founding_team, company_niche,
 num_twitter_followers"""]
Company ID,Description,Company Name,HQ Post Code,Primary Industry Code,
Year Founded,Growth Rate,Size Multiple,Last Financing Size,Company Name,
Majestic Referring Domains,
Facebook Likes,Twitter Followers,Employees,Total Raised,VC_invested,
Twitter_Username
